"""empty message

Revision ID: 17722693b3f6
Revises: 1306e5201255
Create Date: 2022-06-09 21:37:31.130544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17722693b3f6'
down_revision = '1306e5201255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'castinglist', ['name'])
    op.create_unique_constraint(None, 'movielist', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movielist', type_='unique')
    op.drop_constraint(None, 'castinglist', type_='unique')
    # ### end Alembic commands ###
